import React from 'react'
import Work from '../Component/Work'
import Navbar from '../Component/Navbar'
import Footer from '../Component/Footer'

export const metadata = {
    title: 'Works',
    description: 'Generated by create next app',
  }

function work() {
  return (
    <div>
        <Navbar/>
        <Work/>
        <Footer/>
    </div>
  )
}

export default work