import React from 'react'
import Awards from '../Component/Awards'
import Navbar from '../Component/Navbar'
import Footer from '../Component/Footer'

export const metadata = {
    title: 'Awards',
    description: 'Generated by create next app',
  }

function award() {
  return (
    <div>
    <Navbar/>
        <Awards/>
    <Footer/>
    </div>
  )
}

export default award